- .travis.yml
- README.md
Have travis continuous integration and readme badge set up
- Have travisCI integrated with the repo
- Have travisCI readme badge showing build status
n/a
n/a
[#161290993](https://www.pivotaltracker.com/story/show/161290993)
n/a
> #161290993 Setup travis continuous integration with readme badge

- .gitignore
- .sequelizerc
- package-lock.json
- package.json
- server/config/babelHook.js
- server/config/config.js
- server/models/index.js
Integrate postgres db engine
* integrate sequelize
* git ignore env file
* integrate postgres db engine
N/A
N/A
[#161290994](https://www.pivotaltracker.com/story/show/161290994)
N/A
N/A
> #161290994 setup postgres db engine

- .hound.yml
- README.md
Integrate houndCI with this GitHub repository
- add .hound.yml file
- add houndCI badge to readme file
n/a
n/a
[#161290996](https://www.pivotaltracker.com/story/show/161290996)
n/a
> #161290996 Integrate houndCI

- .eslintrc.json
- package-lock.json
- package.json
- This PR setups eslint for the project Valinor-ah-back-end
- Install eslint
- Update eslint config file to adopt Airbnb style guide
- N/A
- N/A
- [#161290993](https://www.pivotaltracker.com/story/show/161290995)
- N/A
- N/A
> #161290995 Setup eslint

- Procfile
- app.json
- index.js
- package-lock.json
- package.json
Set up app Heroku pipeline
- have staging and production apps setup on Heroku
- have commits on develop auto-deploy to staging app
- have review app for PRs set up
- view app on https://valinor-ah-backend-staging.herokuapp.com/
I have deleted the db connection logic in the root `index.js` file. I did this because it uses an env variable `MONGODB_URI` which doesn't currently exist in the production environment, seeing as we're going to be using postgres for the project and this was preventing the app from running.
[#161290997](https://www.pivotaltracker.com/story/show/161290997)
N/A
> #161290997 Deploy base app to Heroku

- package-lock.json
- package.json
- test/sample.test.js
Setup unit testing
- add mocha and chai/chai-http to the project
- add test script
N/A
N/A
[#161290998](https://www.pivotaltracker.com/n/projects/2205593/stories/161290998)
N/A
N/A
> #161290998 Setup unit testing

- .travis.yml
Update TravisCI to run tests
- add a script to run tests on TravisCI
N/A
N/A
[#161477688](https://www.pivotaltracker.com/story/show/161477688)
N/A
N/A
> #161477688 Update TravisCI to run tests

- .travis.yml
- README.md
- package-lock.json
- package.json
Integrate coveralls into this repository
- install istanbul package to collect coverage information
- install mocha lcov reporter package to report coverage information
- add coveralls coverage badge to readme file
- add scripts in .travis.yml to run coverage & coverage reporting
n/a
n/a
[#161290999](https://www.pivotaltracker.com/story/show/161290999)
Coverage report
Readme badge
n/a
> #161290999 Integrate Coveralls

- .gitignore
- index.js
- package-lock.json
- package.json
- server/helpers/sendEmail.js
- test/sample.test.js
- test/server/helpers/sendEmail.test.js
Implement helper function to send email to users
- Have email sent to user when helper function is called with valid user object and message
- Clone the repo
- Checkout the branch `$ git checkout feature/161544103/send-email-to-user`
- Run `$ npm install` to install necessary packages
- Run `$ npm test` to run the function's tests
- Helper function is `sendEmail(user, message)` that returns an error object or null if successful.
- Param `user` will be an object of schema:
```
{
id: bf672b87-7d50-4baa-a12b-990f58f3c7f8,
email: test@example.com,
}
```
- Param `message` will be an object of schema:
```
{
subject: 'Welcome to Author\'s Haven! Confirm your Email',
body: 
`<strong>
Click <a href="${verificationLink}">here</a> to verify your email
</strong>`    
}
``` …
> #161544103 Build helper function to send emails

- app.js
- mockdata/userMockData.js
- package-lock.json
- package.json
- routes/api/users.js
- server/middlewares/UserValidation.js
- test/server/middlewares/UserValidation.test.js
- This PR implements validations on user registration.
- Integrate express validator
- Return descriptive error messages on user signup.
- Update tests to improve coverage
- `npm test`
- N/A
- [#161291004](https://www.pivotaltracker.com/story/show/161504670)
- N/A
> #161291004  Implement validations on user registration

- package-lock.json
- routes/api/users.js
- server/config/config.js
- server/controllers/UsersController.js
- server/middlewares/UserValidation.js
- test/server/controllers/UserController.test.js
- This PR implements the login functionality.
- add tests
- add controllers to login user
- add validations
- make error messsages more descriptive
- `npm test`
- None
-[ #161504670](https://www.pivotaltracker.com/story/show/161504670)
- N/A
[Finishes #161504670]
> #161504670 Implement login-functionality

- .gitignore
- app.js
- package.json
- server/controllers/UsersController.js
- server/helpers/verifyEmailMessage.js
- test/server/controllers/UserController.test.js
- test/server/helpers/verifyEmailMessage.test.js
Implement receive email validation link
- Add email message template
- Integrate signup feature with sending email validation link
- npm test
- npm run start:dev
N/A
[#61291003](https://www.pivotaltracker.com/story/show/161291003)
N/A
> #161291003 Implement receive email validation link

- Procfile
- package.json
Fix heroku apps not running
- modify `Procfile` command to run a script that transpiles on heroku before starting.
- view the review [app](https://valinor-ah-backend-stagi-pr-20.herokuapp.com/)
N/A
[#161645906](https://www.pivotaltracker.com/story/show/161645906)
N/A
N/A
> #161645906 Fix Heroku Procfile command

- test/server/routes/facebookLogin.test.js
Fix facebook test bug
- Fix test bug in facebookLogin.test.js file
- npm run test
N/A
[#161747709](https://www.pivotaltracker.com/story/show/161747709)
N/A
N/A
> #161747709 Fix facebook test

- app.js
- package-lock.json
- package.json
- swagger.json
Document api with swagger
- install swagger-ui-express
- add swagger.json
- implement swagger api documentation
[API documentation](https://valinor-ah-backend-staging.herokuapp.com/api-docs/)
N/A
[#161291000](https://www.pivotaltracker.com/story/show/161291000)
N/A
> #161291000 Document api with swagger

- app.js
- mockdata/facebookMockData.js
- mockdata/twitterMockData.js
- package-lock.json
- package.json
- server/config/twitterPassportRoutes.js
- server/helpers/twitterCallback.js
- server/migrations/20181029191911-create-user.js
- server/models/user.js
- server/routes/api/users.js
- test/server/routes/twitterLogin.test.js
Add the twitter social login feature
- add tests
- add twitter routes
- add twitter strategy
- add twitter callback
- set fullName column to accept nulls
Run `npm start` to start the server
Navigate to  [http://localhost:3000/api/v1/auth/twitter](http://localhost:3000/api/v1/auth/twitter) on your browser
N/A
[#161648143](https://www.pivotaltracker.com/story/show/161648143)
N/A
N/A
> #161648143 Build Twitter Social Login

- .babelrc
- package-lock.json
- package.json
- server/config/babelHook.js
- server/controllers/ArticleController.js
- server/controllers/UsersController.js
- server/routes/api/articles.js
- server/routes/api/index.js
- server/seeders/20181108130344-users.js
- server/seeders/20181108163703-articles.js
- test/server/controllers/ArticleController.test.js
- test/server/models/article.test.js
- This PR fetches an article either by id or slug
- add a controller to fetch an article
- add seed data
- add tests
- `npm test`
- None
- #161747569
- None
> #161747569 Get an article 

- server/migrations/20181109171415-create-comment.js
- server/models/article.js
- server/models/comment.js
- server/models/user.js
- server/seeders/20181109175835-comments.js
- test/server/models/comments.test.js
Set up comment model
- add migration files
- add comment model
- associate comment model with article model
- associate comment model with user model
Run `npm test`
N/A
[#161837489](https://www.pivotaltracker.com/story/show/161837489)
N/A
> #161837489 Setup comment model

- .gitignore
- package-lock.json
- package.json
- server/config/googlePassportRoutes.js
- server/helpers/googleCallback.js
- server/routes/api/users.js
- test/server/routes/googleLogin.test.js
Implement the Google sign up functionality using passport
- Have the google sign up route `/api/v1/auth/google` working
- clone this repo, cd into the branch `feature/161648089/implement-google-login`
- use postman(or any api testing tool) to test the google signup route `GET /api/v1/auth/google`
N/A
[#161648089](https://www.pivotaltracker.com/story/show/161648089)
N/A
>  #161648089 Implement signup with google account

- app.js
- server/controllers/UsersController.js
- server/middlewares/confirmUser.js
- server/routes/api/users.js
- server/seeders/20181108130344-users.js
- test/server/controllers/UserController.test.js
Build the functionality to get all users' profiles
- Have the endpoint `GET /api/v1/users` working— returning an array of user profiles
- Have middleware to verify user exists and user email is confirmed working
- clone this repo, cd into this branch `feature/161291017/view-all-profiles`
- use postman(or any api testing tool) to test the routes
- first sign up a user using `POST http://localhost:3000/api/v1/users/signup`
- verify the user `POST http://localhost:3000/api/v1/users/verify?token={token}`
- get the list of users `GET http://localhost:3000/api/v1/users`
N/A
[#161291017](https://www.pivotaltracker.com/story/show/161291017)
N/A
> #161291017 Build list users feature

- package-lock.json
- package.json
- server/controllers/ArticleController.js
- server/migrations/20181029191911-create-user.js
- server/models/article.js
- server/models/user.js
- server/routes/api/articles.js
- server/routes/api/index.js
- server/seeders/20181108132857-articles.js
- test/server/controllers/ArticleController.test.js
- test/server/routes/facebookLogin.test.js
- test/server/routes/googleLogin.test.js
- test/server/routes/twitterLogin.test.js
Have `/api/v1/articles` route working
- create `/api/v1/articles` route
- create fetch articles controller
- create tests for fetch articles route
- correct error thrown by twitter test
- `npm start` to start your server
- use your browser or postman to hit the`localhost:{PORT}/api/v1/articles` route
- None
- [#161747559](https://www.pivotaltracker.com/story/show/161747559)
- None
> #161747559 Fetch all articles route

- app.js
- mockdata/articleMockData.js
- package-lock.json
- package.json
- server/controllers/ArticleController.js
- server/middlewares/ArticleValidation.js
- server/routes/api/articles.js
- server/routes/api/index.js
- test/server/controllers/ArticleController.test.js
- test/server/helpers/tokenUtils.test.js
- test/server/routes/googleLogin.test.js
- test/server/routes/twitterLogin.test.js
Implements the create article feature
Have the create article endpoint `POST api/v1/articles` working.
- clone the repository, cd into it, checkout this branch `feature/161291009/user-create-articles`
- use postman(or any api testing tool) to test the following routes route
- create a user using the route `POST http://localhost:3000/api/v1/users/signup` providing necessary request body as shown in screen shots below
- create an article with the route `POST http://localhost:3000/api/v1/articles` providing necessary request body, as well as the token in the `Authorization` header as shown in screen shots below.
N/A …
>  #161291009 Build create article route

- .gitignore
- mockdata/ratingMockData.js
- server/migrations/20181106124148-create-article.js
- server/migrations/20181107082847-create-rating.js
- server/models/article.js
- server/models/rating.js
- server/models/user.js
- server/seeders/20181109205134-ratings.js
- test/server/models/rating.test.js
Have a ratings model for database migrations
- add tests
- add model
- add migration
Run `npm test` to check that model tests are passing
N/A
[#161747400](https://www.pivotaltracker.com/story/show/161747400)
N/A
N/A
> #161747400 Setup the ratings model

- server/controllers/ArticleController.js
- server/middlewares/validateArticleId.js
- server/routes/api/articles.js
- server/seeders/20181108132857-articles.js
- test/server/controllers/ArticleController.test.js
Build the end point to like/dislike an article
- Have the endpoint `POST /articles/:slug/:action` to like or dislike an article
- Ensure that the user can only like or unlike an article only once
- clone this repo, cd into it and checkout the branch `feature/161291012/user-like-dislike-article`
- run npm install to install required packages
- run npm start to start up the server
- use postman(or any api testing tool) to test the following routes
- first sign up a user using POST `http://localhost:{PORT}/api/v1/users/signup` getting the valid credentials
- then test the route using `POST http://localhost:{PORT}/api/v1/articles/:slug/:action`
where `:slug` is the article slug and `:action` can be `like` or `dislike`
N/A …
>  #161291012 Build Like/Dislike article Functionality

- mockdata/followMockData.js
- server/migrations/20181112154102-create-follow.js
- server/models/follow.js
- server/models/user.js
- test/server/models/follow.test.js
- This PR sets up the follow author model.
- add follow model
- add migrations
- add unit tests for follow model
- `npm test`
- N/A
-[ #161861589](https://www.pivotaltracker.com/story/show/161861589)
- N/A
- N/A
> #161861589 Setup follow author model

- server/migrations/20181113154825-create-bookmark.js
- server/models/article.js
- server/models/bookmark.js
- server/models/user.js
- server/seeders/20181113160955-bookmarks.js
- test/server/models/bookmark.test.js
Add bookmark model
- add migration file
- add bookmark model file
- test the model
* clone this repo, cd into it and checkout the branch feature/161291011/comment-on-articles
* set up your .env variables and local database
* run npm install to install required packages
* run npm test to run the test
N/A
[#161861590](https://www.pivotaltracker.com/story/show/161861590)
N/A
> #161861590 Add bookmark model

- mockdata/userMockData.js
- package-lock.json
- package.json
- server/controllers/FollowController.js
- server/helpers/errorResponse.js
- server/helpers/getfollowViews.js
- server/middlewares/UserValidation.js
- server/migrations/20181029191911-create-user.js
- server/models/follow.js
- server/models/user.js
- server/routes/api/users.js
- test/server/controllers/FollowController.test.js
- test/server/helpers/errorResponse.test.js
- test/server/models/follow.test.js
- This PR implements the follow author functionality
- Authors can only be followed if they have published at least 5 articles
- Authors can follow Author provided they meet the above criteria
- Users can follow Authors
- Every user can see both who are following them and who they followed.
- `npm test`
- None
- [#161291013](https://www.pivotaltracker.com/story/show/161291013)
- N/A
> #161291013 Implement follow functionality

- mockdata/userMockData.js
- server/controllers/UsersController.js
- server/helpers/emailTemplates.js
- server/middlewares/UserValidation.js
- server/migrations/20181029191911-create-user.js
- server/models/user.js
- server/routes/api/users.js
- test/server/controllers/ArticleController.test.js
- test/server/controllers/CommentController.test.js
- test/server/controllers/FollowController.test.js
- test/server/controllers/UserController.test.js
- test/server/helpers/verifyEmailMessage.test.js
- test/server/middlewares/UserValidation.test.js
- test/server/models/rating.test.js
Change user login to use email link
- add tests
- add routes
- add controller methods
- add validation
N/A
N/A
[#161839962](https://www.pivotaltracker.com/n/projects/2205593/stories/161839962)
N/A
> #161839962 Update User Login to Use Email Link

- package-lock.json
- server/controllers/ArticleController.js
- server/controllers/CommentController.js
- server/middlewares/confirmUser.js
- server/middlewares/validateResourceId.js
- server/migrations/20181114173514-create-commentevent.js
- server/models/article.js
- server/models/comment.js
- server/models/commentevent.js
- server/routes/api/articles.js
- server/routes/api/comments.js
- server/routes/api/users.js
- test/server/controllers/CommentController.test.js
- test/server/controllers/UserController.test.js
Make the edit history of comment trackable
- Build the edit comment route to make update to a single comment
- Build the `CommentEvents` table, model and associations
- Build the get single comment route to get a comment's value and history
- Update the Get article controller to eager load comments in its response
- Refactor the Article Id validation to make it reusable for any resource Id
- clone the repo, checkout into this branch `feature/161291031/track-comment-edit-history`
- setup your local db and .env variables
- run `npm db-init` then `npm start` to start up the server
- using postman, do the following:
- sign up a user, create a comment, edit it
- test the get comment route using the `http://localhost:{POST}/api/v1/comments/3`
N/A …
> #161291031 Implement comment edit history functionality

- .babelrc
- package.json
- server/controllers/ArticleController.js
- test/server/controllers/ArticleController.test.js
- This PR adds the author information to the create article response.
- update tests
- add logic to include author information to create article response
- `npm test`
- None
- [#162008149](https://www.pivotaltracker.com/story/show/162008149)
- N/A
> #162008149 Bug fix-include author information in create article response

- server/controllers/TagController.js
- server/routes/api/articles.js
- test/server/controllers/TagController.test.js
Implement get all tags
- write test for TagController
- add TagController
- clone this repo, cd into the branch `feature/162030152/view-all-tags`
- use postman to test the google signup route `GET /api/v1/articles/tags`
N/A
[#162030152](https://www.pivotaltracker.com/story/show/162030152)
N/A
> #162030152 Implement get all tags

- package.json
- server/controllers/UsersController.js
- server/routes/api/users.js
- server/seeders/20181108130344-users.js
- test/server/controllers/ArticleController.test.js
- test/server/controllers/CommentController.test.js
- test/server/controllers/FollowController.test.js
- test/server/controllers/RatingsController.test.js
- test/server/controllers/UserController.test.js
Fix bugs in the user log in process
- add a check for email confirmation
- refactor route handler to not create new user if an email is not found in the database
- update login route tests
After cloning the repo, set up the database and environment variables
cd into the folder and run `npm install`
You can also test that the endpoint works as follows:
- Open postman
- Select POST
- Type in the route `http://localhost:3000/api/v1/users/login`
- Click the link that was sent to the email address you provided
- You should be logged in provided your email has been verified
N/A
[#162015912](https://www.pivotaltracker.com/story/show/162015912)
N/A
> #162015912 Fix for users logging in without email confirmation

- server/controllers/CommentController.js
- server/middlewares/addReadingStats.js
- server/middlewares/tokenUtils.js
- server/migrations/20181109171415-create-comment.js
- server/models/comment.js
- server/seeders/20181109175835-comments.js
Implements the backend side of the highlight and comment feature
- add inlineComment to comment model
- add inlineComment to post comment controller
- fix bug in readingStats
- fix bug in verifyToken middleware
- clone this repo
- run `npm i`
- run `npm start`
- run `npm run db-init`
- hit the `api/v1/articles/:{articleId}` route
- None
[#161291028](https://www.pivotaltracker.com/story/show/161291028)
- None
> #161291028 highlight and comment

- server/helpers/getRoleId.js
- server/middlewares/validateAccess.js
- server/migrations/20181106124148-create-article.js
- server/models/article.js
- test/server/controllers/UserController.test.js
- test/server/helpers/getRoleId.test.js
- test/server/middlewares/validateAccess.test.js
- This PR implements the role-based functionality
- Users get automatically upgraded to Authors once they published 5 articles.
- Create middleware that validates for admin access before carrying out admin related operations
- `npm test`
- None
- [#161291027](https://www.pivotaltracker.com/story/show/161291027)
- None
- None
> #161291027 Implement role based functionality

- package-lock.json
- server/controllers/CommentController.js
- server/middlewares/validateResourceId.js
- server/migrations/20181114173514-create-commentevent.js
- server/routes/api/comments.js
- server/seeders/20181108130344-users.js
- server/seeders/20181109175835-comments.js
- test/server/controllers/CommentController.test.js
- test/server/middlewares/validateAccess.test.js
Have an endpoint to delete comments on articles
- add tests
- add routes
- add controller methods
- add route validation
- Clone the repository, cd into it.
- Set up your .env variables and local database
- Run `npm install` to install required packages
- Run `npm start` to fire up the server
- Use Postman(or any API testing tool) to test the following route
- Delete a comment using the route `DELETE http://localhost:3000/api/v1/articles/:articleId/comments/:commentId`, providing necessary params.
N/A
[#162168558](https://www.pivotaltracker.com/story/show/162168558)
N/A
> #162168558 Build out endpoint to delete comments on articles

- mockdata/userMockData.js
- package-lock.json
- package.json
- server/controllers/UsersController.js
- server/helpers/checkToken.js
- server/helpers/emailTemplates.js
- server/middlewares/tokenUtils.js
- server/middlewares/validateAccess.js
- server/migrations/20181029191911-create-user.js
- server/models/user.js
- server/routes/api/users.js
- server/seeders/20181108130344-users.js
- test/server/controllers/ArticleController.test.js
- test/server/controllers/FollowController.test.js
- test/server/controllers/UserController.test.js
- test/server/middlewares/validateAccess.test.js
Implement the functionality to deactivate, re-activate and delete a user account
- add status column to users table
- add endpoint `PATCH /api/v1/users/:userId/account/action` to modify account status by deactivating, activating or deleting
- ensure only a user can delete, deactivate, or activate his own account
- ensure email link is sent to user if they want to delete their account
- clone the repository, cd into it, checkout this branch `feature/162050416/deactivate-or-delete-account`
- use postman(or any api testing tool) to test the following routes route
- create a user using the route `POST http://localhost:3000/api/v1/users/signup` providing …
> #162050416 Implement user account deactivate/delete feature

- package-lock.json
- server/controllers/ArticleController.js
- server/controllers/CommentController.js
- server/controllers/FollowController.js
- server/controllers/NotificationController.js
- server/helpers/emailTemplates.js
- server/helpers/getNotificationCount.js
- server/middlewares/UserValidation.js
- server/migrations/20181029191911-create-user.js
- server/migrations/20181115163056-create-notification.js
- server/migrations/20181115163859-create-notification-event.js
- server/models/notification.js
- server/models/notificationevent.js
- server/models/user.js
- server/routes/api/index.js
- server/routes/api/notifications.js
- server/routes/api/users.js
- server/seeders/20181108135214-article-likes.js
- server/seeders/20181115165002-notifications.js
- server/seeders/20181115165010-notification-events.js
- test/server/controllers/ArticleController.test.js
- test/server/controllers/NotificationController.test.js
- test/server/controllers/RatingsController.test.js
- test/server/controllers/ReportController.test.js
- test/server/controllers/UserController.test.js
- test/server/models/articleLike.test.js
- test/server/models/notificationevent.test.js
- test/server/models/rating.test.js
Implement receive notification feature
- Write tests for NotifcationEvent model
- Write tests for NotificationController
- Add Notification model
- Add NotificationEvent model
- Implement notification via email
- Add NotificationController
- Add opt-in and opt-out functionality
- Get all notification for a user functionality
- clone the repository, cd into it, checkout this branch feature/161291014/receive-notification
- run npm install to install required packages
- run npm start to start up the server
- use postman(or any api testing tool) to test the following routes route
- create a user using the route POST `http://localhost:3000/api/v1/users/signup` providing necessary request body.
- modify account status PATCH …
> #161291014 Implement receive notifcation feature

- app.js
- server/controllers/CommentController.js
- server/middlewares/ArticleValidation.js
- server/middlewares/ReportValidation.js
- server/routes/api/comments.js
- swagger.json
- test/server/controllers/CommentController.test.js
Update the swagger api documentation
Have all the available endpoints adequately documented on the swagger doc page
- clone the repo
- checkout into this branch
- run `npm install`
- setup environment variables
- run `npm start`
- open up `localhost:3000/api-docs` on your browser
N/A
[162265214](https://www.pivotaltracker.com/story/show/162265214)
N/A
> #162265214 Update Swagger API docs

- server/controllers/UsersController.js
Change login URL to point frontend instead of the backend
- change login URL link
After cloning the repo, cd into the folder and run `npm run start:dev` and then:
- Open postman
- Login via the login route
- The link in the email should now direct you the application front-end
N/A
[#162686442](https://www.pivotaltracker.com/story/show/162686442)
N/A
> #162686442 Change user login url

- server/helpers/emailTemplates.js
- Redirect email link to frontend
- modify href of click here link
- Run `npm start`
N/A
[#162700127](https://www.pivotaltracker.com/story/show/162700127)
N/A
> #162700127 Redirect email link to frontend

- server/controllers/ArticleController.js
- server/controllers/UsersController.js
- server/helpers/cleanupArticlesResponse.js
- server/migrations/20181029191911-create-user.js
- server/models/user.js
- server/routes/api/articles.js
- server/seeders/20181108134214-reading-stats.js
- test/server/controllers/ArticleController.test.js
- test/server/controllers/FollowController.test.js
- test/server/middlewares/addReadingStats.test.js
Build out endpoint to fetch most popular articles
- add endpoint to fetch most popular posts
- add default image to user model
- checkout to this branch
- run `npm start`
- use Postman(or any API testing client) to hit `GET localhost:3000/api/v1/articles/popular`
N/A
[162699653](https://www.pivotaltracker.com/story/show/162699653)
N/A
> #162699653 Implement feature to view most popular posts

- server/controllers/ArticleController.js
- server/helpers/emailTemplates.js
Fix bug in the get an article api endpoint
- fix the bug
- test the functionality
- run `npm start` or `npm run dev to start up the server
N/A
[#162731415](https://www.pivotaltracker.com/story/show/162731415)
N/A
> #162731415 Fix bug in the get an article api endpoint

- server/helpers/emailTemplates.js
Make email templates more professional
- fix up email templates
N/A
N/A
[#162980441](https://www.pivotaltracker.com/story/show/162980441)
N/A
> #162980441 Fix email templates

- server/helpers/emailTemplates.js
Have an endpoint to get single questions from the database
- fix up email link
N/A
N/A
[#162981302](https://www.pivotaltracker.com/story/show/162981302)
N/A
N/A
> #162981302 Fix email link
